config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get 'home/about'=> 'homes#about',as:'about'
  resources:books,only:[:new,:create,:index,:show,:destroy,:edit,:update]
  resources:users,only:[:create,:show,:index,:edit,:update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

  validates :body,
    length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :name,
    length: { minimum: 2, maximum: 20 }
  validates :introduction,
    length: { maximum: 50 }
  validates :email, uniqueness: true
  validates :name, uniqueness: true

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :success, :info, :warning, :danger

  def after_sign_in_path_for(resource)
    current_user
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book=Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
  if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
  else
    @books = Book.all
    render "index"
  end
  end

  def index
    @user=current_user
    @book=Book.new
    @books=Book.all
  end

  def show
    @book=Book.find(params[:id])
    @books=Book.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
  if@book.update(book_params)
     flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
  else

    @books = Book.all
    render "edit"
  end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about

  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
  if@user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
  else
    render "edit"
    flash[:alert] = "error"
  end
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<% if user.errors.any? %>
  <div class = "alert">
    <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="col-md-3">
 <h2>User info</h2>
  <p><%= image_tag user.get_profile_image(100,100) %></p>
   <table class="tabele">
    <tbody>
     <tr></tr>
     <tr>
       <th>name</th>
       <th><%= user.name %></th>
     </tr>
     <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
     </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to edit_user_path(user), class: do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

<h2 class="mt-3">New book</h2>

<form action="/books" accept-charset="UTF-8" method="post">

<% if book.errors.any? %>
  <%= book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: book, url: '/books', method: :post do |f| %>
<div class="form-group">
  <label for="book_title">Title</label>
  <br><%= f.text_field :title %>
</div>
<div class="form-group">
  <label for="book_body">Opinion</label>
  <br><%= f.text_area :body %>
</div>
<div class="form-group">
  <%= f.submit 'Create Book' %>
<% end %>
</div>
</form>
</div>

app/views/books/edit.html.erb
<h2>Editing Book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

  <td><% if @book.user == current_user %>
                  <%= link_to "Show", book_path(@book) %>
                  <% end %></td>
  <td><%= link_to books_path do %>
　     Back
　    <% end %>
　</td>
      <% end %>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
<%= render 'list',book: @book,user:current_user %>

   <div class="col-md-8 offset-md-1">
    <h2 class="mt-3">Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
       <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th colspan="3"></th>
        </tr>
       </thead>
      <tbody>
           <% @books.each do |book| %>
         <tr>
          <td> <%= link_to user_path(book.user.id) do%>
            <%= image_tag book.user.get_profile_image(100,100) %>
               <% end %>
          </td>
          <td><%= link_to book.title,"/books/#{book.id}" %></td>
          <td><%= book.body %></td>
         </tr>
           <% end %>
      </tbody>
     </table>
    </div>
   </div>
  </div>
 </miain>

app/views/books/new.html.erb
<h2>User info</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="profile-container">
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <p><%= link_to "edit", edit_user_path(@user) %></p>
</div>

<h1>New Book</h1>
<!-- form_with部分 -->
<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<main>
  <p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">

<%= render 'list',book: @books,user: @book.user %>

<div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody>
  		    <tr>
  		      <td>
  		         <%= link_to user_path(@book.user.id) do%>
  		           <%= image_tag @book.user.get_profile_image(100,100)%>
  		           <br><%= @book.user.name %>
  		         <% end %>
  		      </td>
  		      <td><%= link_to @book.title, users_path(@book) %></td>
  		      <td><%= @book.body %></td>
  		      <td><% if @book.user == current_user %>
                  <%= link_to "Edit", edit_book_path(@book) %>
                  <% end %></td>
  		      <td><% if @book.user == current_user %>
                  <%= link_to "Destroy", book_path(@book), method: :delete %>
                  <% end %></td>
  		    </tr>
        </tbody>
      </table>
    </div>
  </div>
 </div>
<table class="table table-striped">
<div class="text-success">
  <%= flash[:notice] %>
</div>
<div class="text-danger">
  <%= flash[:alret] %>
</div>
</main>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3  mx-auto">
        Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
      <main>
          <div class="container">
            <div class="row">
              <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
                <h1>welcome to
                　 <i class="fas fa-book"></i>
                  <strong>Bookers</strong>
                  !!
                </h1>
                <p>In
                 <i class="fas fa-book"></i>
                  <strong>Bookers</strong>
                  ,
                  </p>
                  <p>you can share and exchange  your opinions , inpressions , and emotions</p>
                  <p> about various books!</p>
                  <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                    <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
                </div>
                <div class="row">
                    <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
                </div>
             </div>
          </div>
       </div>
    </div>
</main>
<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
</body>
</html>

app/views/users/edit.html.erb
<html class="fontawesome-i2svg-active fontawesome-12svg-complete">
<main>
  <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <% if @user.errors.any? %>
        <div class = "alert">
        <ul>
          <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
          <% end %>
        </ul>
        </div>
         <% end %>
          <h2>User info</h2>
            <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
        </div>
        <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
            <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介"%>
        </div>
        <div class="form-group">
          <label for="inputImage">ProfileImage</label>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
        </div>
        <div class="form-group">
            <%= f.submit "Update User" %>
        </div>
            <% end %>
        </div>
      </div>
    </div>
  </main>
  </html>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">

<%= render 'books/list', book: @book,user:current_user %>

<div class="col-md-8 offset-md-1">
    <h2 class="mt-3">Users</h2>
    <table class="table table-hover table-inverse">
      <thead>
       <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th colspan="3"></th>
        </tr>
       </thead>
      <tbody>
           <% @user.each do |user| %>
         <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user)%></td>
         </tr>
           <% end %>
      </tbody>
     </table>
    </div>
   </div>
  </div>
 </miain>

app/views/users/show.html.erb
<main>
  <p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
<%= render 'books/list', book: @book,user: @user %>


 <div class="col-md-8 offset-md-1">
 <h2 class="mt-3">Books</h2>
 <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(@user.id) do%>
            <%= image_tag @user.get_profile_image(100,100) %>
          <% end %>
        </td>
        <td><%= link_to book.title,book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book) %></td>
      </tr>
    <% end %>
    </div>
  </tbody>
  </table>